-- Questions the listing assistant could not answer, for the dealer to answer.
-- Additive only. Generated by `prisma migrate diff`, with the drift that diff
-- always reports for the hand-written search migrations (the searchVector
-- default and the trigram index names) left out on purpose.

-- CreateEnum
CREATE TYPE "BuyerQuestionStatus" AS ENUM ('OPEN', 'ANSWERED', 'DISMISSED');

-- CreateTable
CREATE TABLE "BuyerQuestion" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "carId" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "questionKey" TEXT NOT NULL,
    "locale" TEXT NOT NULL,
    "askCount" INTEGER NOT NULL DEFAULT 1,
    "lastAskedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "BuyerQuestionStatus" NOT NULL DEFAULT 'OPEN',
    "answer" TEXT,
    "appliesToAllCars" BOOLEAN NOT NULL DEFAULT false,
    "answeredById" TEXT,
    "answeredAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BuyerQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BuyerQuestion_organizationId_status_lastAskedAt_idx" ON "BuyerQuestion"("organizationId", "status", "lastAskedAt");

-- CreateIndex
CREATE INDEX "BuyerQuestion_organizationId_status_appliesToAllCars_idx" ON "BuyerQuestion"("organizationId", "status", "appliesToAllCars");

-- CreateIndex
CREATE UNIQUE INDEX "BuyerQuestion_carId_questionKey_key" ON "BuyerQuestion"("carId", "questionKey");

-- AddForeignKey
ALTER TABLE "BuyerQuestion" ADD CONSTRAINT "BuyerQuestion_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BuyerQuestion" ADD CONSTRAINT "BuyerQuestion_carId_fkey" FOREIGN KEY ("carId") REFERENCES "Car"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BuyerQuestion" ADD CONSTRAINT "BuyerQuestion_answeredById_fkey" FOREIGN KEY ("answeredById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

