/**
 * Egypt's governorates and the cities a dealership can be in, with both
 * display names.
 *
 * This replaces three round-trips to api.countrystatecity.in during onboarding.
 * The product is Egypt-only, so fetching a worldwide country list behind an API
 * key — on the critical path of signing a dealer up, where an outage or a
 * lapsed key silently empties the dropdown — bought nothing.
 *
 * It is also the single source of truth for place names. The dropdown, the
 * display lookup and the search aliases all read this file, so a value that can
 * be chosen is always a value that can be translated: the coverage gap that
 * arises from keeping an option list and a message catalogue in separate places
 * cannot happen here.
 *
 * ## Why the names are curated rather than imported
 *
 * The API's Egyptian city list mixed governorate capitals with Cairo
 * neighbourhoods, listed districts twice ("Disūq" and "Markaz Disūq" are one
 * place), and transliterated inconsistently — "Al Manşūrah" beside "Mersa
 * Matruh". Matching those spellings to Arabic automatically produced confident
 * nonsense: Abu Qir matched Abusir, Heliopolis matched Hermopolis, and Rehab
 * matched Dahab, which is on the other side of the country. So the list below
 * is written out, using the spellings Egyptians actually write.
 *
 * ## What is stored
 *
 * `Organization.region` holds the governorate `code` and `Organization.city`
 * holds the city `slug`. Neither column holds a display name, so nothing has to
 * be re-spelled to be translated, and a dealer switching the site to Arabic
 * sees their own address change language.
 */

export interface EgyptCity {
  /** Stored in `Organization.city`. Stable; never re-generate these. */
  slug: string;
  en: string;
  ar: string;
}

export interface EgyptGovernorate {
  /** ISO 3166-2:EG subdivision code, stored in `Organization.region`. */
  code: string;
  en: string;
  ar: string;
  cities: readonly EgyptCity[];
}

const city = (slug: string, en: string, ar: string): EgyptCity => ({
  slug,
  en,
  ar,
});

export const EGYPT_COUNTRY_CODE = "EG";

export const EGYPT_GOVERNORATES: readonly EgyptGovernorate[] = [
  {
    code: "C",
    en: "Cairo",
    ar: "القاهرة",
    cities: [
      city("cairo", "Cairo", "القاهرة"),
      city("new-cairo", "New Cairo", "القاهرة الجديدة"),
      city("nasr-city", "Nasr City", "مدينة نصر"),
      city("heliopolis", "Heliopolis", "مصر الجديدة"),
      city("maadi", "Maadi", "المعادي"),
      city("zamalek", "Zamalek", "الزمالك"),
      city("shubra", "Shubra", "شبرا"),
      city("helwan", "Helwan", "حلوان"),
      city("el-rehab", "El Rehab", "الرحاب"),
      city("madinaty", "Madinaty", "مدينتي"),
      city("el-shorouk", "El Shorouk", "الشروق"),
      city("badr-city", "Badr City", "مدينة بدر"),
      city("el-matareya", "El Matareya", "المطرية"),
      city("ain-shams", "Ain Shams", "عين شمس"),
      city("el-marg", "El Marg", "المرج"),
      city("maasara", "El Maasara", "المعصرة"),
      city("tura", "Tura", "طرة"),
      city("downtown-cairo", "Downtown Cairo", "وسط البلد"),
      city("new-capital", "New Administrative Capital", "العاصمة الإدارية الجديدة"),
      city("old-cairo", "Old Cairo", "مصر القديمة"),
      city("fifth-settlement", "Fifth Settlement", "التجمع الخامس"),
      city("mokattam", "Mokattam", "المقطم"),
      city("15-may-city", "15 May City", "15 مايو"),
      city("al-azbakeyah", "Al Azbakeyah", "الأزبكية"),
      city("al-basatin", "Al Basatin", "البساتين"),
      city("tebin", "Tebin", "التبين"),
      city("el-khalifa", "El-Khalifa", "الخليفة"),
      city("el-darrasa", "El Darrasa", "الدراسة"),
      city("aldarb-alahmar", "Aldarb Alahmar", "الدرب الأحمر"),
      city("zawya-al-hamra", "Zawya al-Hamra", "الزاوية الحمراء"),
      city("el-zaytoun", "El-Zaytoun", "الزيتون"),
      city("sahel", "Sahel", "الساحل"),
      city("el-salam", "El Salam", "السلام"),
      city("sayeda-zeinab", "Sayeda Zeinab", "السيدة زينب"),
      city("el-sharabeya", "El Sharabeya", "الشرابية"),
      city("el-daher", "El Daher", "الظاهر"),
      city("ataba", "Ataba", "العتبة"),
      city("ezbet-el-nakhl", "Ezbet el Nakhl", "عزبة النخل"),
      city("manyal", "Manyal", "المنيل"),
      city("mosky", "Mosky", "الموسكي"),
      city("nozha", "Nozha", "النزهة"),
      city("waily", "Waily", "الوايلي"),
      city("bab-al-shereia", "Bab al-Shereia", "باب الشعرية"),
      city("bolaq", "Bolaq", "بولاق"),
      city("garden-city", "Garden City", "جاردن سيتي"),
      city("hadayek-el-kobba", "Hadayek El-Kobba", "حدائق القبة"),
      city("dar-al-salam", "Dar Al Salam", "دار السلام"),
      city("abdeen", "Abdeen", "عابدين"),
      city("abaseya", "Abaseya", "العباسية"),
      city("mansheya-nasir", "Mansheya Nasir", "منشية ناصر"),
      city("kasr-el-nile", "Kasr El Nile", "قصر النيل"),
      city("katameya", "Katameya", "القطامية"),
      city("rod-alfarag", "Rod Alfarag", "روض الفرج"),
      city("sheraton", "Sheraton", "شيراتون"),
      city("el-gamaleya", "El-Gamaleya", "الجمالية"),
      city("helmeyat-alzaytoun", "Helmeyat Alzaytoun", "الحلمية"),
      city("new-nozha", "New Nozha", "النزهة الجديدة"),
    ],
  },
  {
    code: "GZ",
    en: "Giza",
    ar: "الجيزة",
    cities: [
      city("giza", "Giza", "الجيزة"),
      city("6th-of-october", "6th of October City", "مدينة السادس من أكتوبر"),
      city("sheikh-zayed", "Sheikh Zayed City", "مدينة الشيخ زايد"),
      city("dokki", "Dokki", "الدقي"),
      city("mohandessin", "Mohandessin", "المهندسين"),
      city("haram", "Haram", "الهرم"),
      city("faisal", "Faisal", "فيصل"),
      city("imbaba", "Imbaba", "إمبابة"),
      city("agouza", "Agouza", "العجوزة"),
      city("hawamdeya", "El Hawamdeya", "الحوامدية"),
      city("badrashin", "El Badrashin", "البدرشين"),
      city("saff", "El Saff", "الصف"),
      city("atfih", "Atfih", "أطفيح"),
      city("ausim", "Ausim", "أوسيم"),
      city("kerdasa", "Kerdasa", "كرداسة"),
      city("6th-of-october-gz", "6th of October", "6 أكتوبر"),
      city("sheikh-zayed-gz", "Sheikh Zayed", "الشيخ زايد"),
      city("new-sphinx", "New Sphinx", "سفنكس الجديدة"),
      city("hadayek-october", "Hadayek October", "حدائق أكتوبر"),
      city("al-ayat", "Al Ayat", "العياط"),
      city("al-bawaiti", "Al-Bawaiti", "الباويطي"),
      city("manshiyet-al-qanater", "Manshiyet Al Qanater", "منشأة القناطر"),
      city("abu-nomros", "Abu Nomros", "أبو النمرس"),
      city("kafr-ghati", "Kafr Ghati", "كفر غطاطي"),
      city("manshiyet-al-bakari", "Manshiyet Al Bakari", "منشأة البكاري"),
      city("warraq", "Warraq", "الوراق"),
      city("boulaq-dakrour", "Boulaq Dakrour", "بولاق الدكرور"),
      city("al-wahat-al-baharia", "Al Wahat Al Baharia", "الواحات البحرية"),
      city("omraneya", "Omraneya", "العمرانية"),
      city("moneeb", "Moneeb", "المنيب"),
      city("bin-alsarayat", "Bin Alsarayat", "بين السرايات"),
      city("kit-kat", "Kit Kat", "الكيت كات"),
      city("abu-rawash", "Abu Rawash", "أبو رواش"),
      city("hadayek-alahram", "Hadayek Alahram", "حدائق الأهرام"),
      city("haraneya", "Haraneya", "الحرانية"),
      city("saft-allaban", "Saft Allaban", "صفط اللبن"),
      city("smart-village", "Smart Village", "القرية الذكية"),
      city("ard-ellwaa", "Ard Ellwaa", "أرض اللواء"),
    ],
  },
  {
    code: "ALX",
    en: "Alexandria",
    ar: "الإسكندرية",
    cities: [
      city("alexandria", "Alexandria", "الإسكندرية"),
      city("borg-el-arab", "Borg El Arab", "برج العرب"),
      city("new-borg-el-arab", "New Borg El Arab", "برج العرب الجديدة"),
      city("abu-qir", "Abu Qir", "أبو قير"),
      city("montaza", "Montaza", "المنتزه"),
      city("sidi-bishr", "Sidi Bishr", "سيدي بشر"),
      city("el-raml", "El Raml", "الرمل"),
      city("agami", "Agami", "العجمي"),
      city("smouha", "Smouha", "سموحة"),
      city("miami", "Miami", "ميامي"),
      city("downtown-alexandria", "Downtown Alexandria", "وسط الإسكندرية"),
      city("amreya", "Amreya", "العامرية"),
      city("al-ibrahimeyah", "Al Ibrahimeyah", "الإبراهيمية"),
      city("azarita", "Azarita", "الأزاريطة"),
      city("anfoushi", "Anfoushi", "الأنفوشي"),
      city("dekheila", "Dekheila", "الدخيلة"),
      city("el-soyof", "El Soyof", "السيوف"),
      city("el-labban", "El Labban", "اللبان"),
      city("al-mafrouza", "Al Mafrouza", "المفروزة"),
      city("mansheya", "Mansheya", "المنشية"),
      city("naseria", "Naseria", "الناصرية"),
      city("ambrozo", "Ambrozo", "أمبروزو"),
      city("bab-sharq", "Bab Sharq", "باب شرق"),
      city("stanley", "Stanley", "ستانلي"),
      city("shads", "Shads", "شدس"),
      city("gheet-alenab", "Gheet Alenab", "غيط العنب"),
      city("fleming", "Fleming", "فلمينج"),
      city("victoria", "Victoria", "فيكتوريا"),
      city("camp-shizar", "Camp Shizar", "كامب شيزار"),
      city("karmooz", "Karmooz", "كرموز"),
      city("mahta-alraml", "Mahta Alraml", "محطة الرمل"),
      city("mina-el-basal", "Mina El-Basal", "مينا البصل"),
      city("asafra", "Asafra", "العصافرة"),
      city("bakos", "Bakos", "بكوس"),
      city("boulkly", "Boulkly", "بولكلي"),
      city("cleopatra", "Cleopatra", "كليوباترا"),
      city("glim", "Glim", "جليم"),
      city("al-mamurah", "Al Mamurah", "المعمورة"),
      city("al-mandara", "Al Mandara", "المندرة"),
      city("moharam-bek", "Moharam Bek", "محرم بك"),
      city("elshatby", "Elshatby", "الشاطبي"),
      city("sidi-gaber", "Sidi Gaber", "سيدي جابر"),
      city("north-coast", "North Coast", "الساحل الشمالي"),
      city("alhadra", "Alhadra", "الحضرة"),
      city("alattarin", "Alattarin", "العطارين"),
      city("sidi-kerir", "Sidi Kerir", "سيدي كرير"),
      city("elgomrok", "Elgomrok", "الجمرك"),
      city("al-max", "Al Max", "المكس"),
      city("marina", "Marina", "مارينا"),
    ],
  },
  {
    code: "KB",
    en: "Qalyubia",
    ar: "القليوبية",
    cities: [
      city("banha", "Banha", "بنها"),
      city("shubra-el-kheima", "Shubra El Kheima", "شبرا الخيمة"),
      city("qalyub", "Qalyub", "قليوب"),
      city("el-obour", "El Obour", "العبور"),
      city("khanka", "El Khanka", "الخانكة"),
      city("qanater-khayreya", "El Qanater El Khayreya", "القناطر الخيرية"),
      city("shibin-el-qanater", "Shibin El Qanater", "شبين القناطر"),
      city("kafr-shukr", "Kafr Shukr", "كفر شكر"),
      city("tukh", "Tukh", "طوخ"),
      city("new-obour", "New Obour", "العبور الجديدة"),
      city("qaha", "Qaha", "قها"),
      city("khosous", "Khosous", "الخصوص"),
      city("mostorod", "Mostorod", "مسطرد"),
    ],
  },
  {
    code: "SHR",
    en: "Sharqia",
    ar: "الشرقية",
    cities: [
      city("zagazig", "Zagazig", "الزقازيق"),
      city("10th-of-ramadan", "10th of Ramadan City", "مدينة العاشر من رمضان"),
      city("bilbeis", "Bilbeis", "بلبيس"),
      city("abu-hammad", "Abu Hammad", "أبو حماد"),
      city("abu-kabir", "Abu Kabir", "أبو كبير"),
      city("faqous", "Faqous", "فاقوس"),
      city("hehia", "Hehia", "ههيا"),
      city("minya-el-qamh", "Minya El Qamh", "منيا القمح"),
      city("diyarb-negm", "Diyarb Negm", "ديرب نجم"),
      city("el-qurein", "El Qurein", "القرين"),
      city("10th-of-ramadan-shr", "10th of Ramadan", "العاشر من رمضان"),
      city("mashtoul-el-souq", "Mashtoul El Souq", "مشتول السوق"),
      city("qenaiat", "Qenaiat", "القنايات"),
      city("el-salihia-el-gedida", "El Salihia El Gedida", "الصالحية الجديدة"),
      city("al-ibrahimiyah", "Al Ibrahimiyah", "الإبراهيمية"),
      city("kafr-saqr", "Kafr Saqr", "كفر صقر"),
      city("awlad-saqr", "Awlad Saqr", "أولاد صقر"),
      city("husseiniya", "Husseiniya", "الحسينية"),
      city("san-alhajar-alqablia", "San Alhajar Alqablia", "صان الحجر القبلية"),
      city("manshayat-abu-omar", "Manshayat Abu Omar", "منشأة أبو عمر"),
    ],
  },
  {
    code: "DK",
    en: "Dakahlia",
    ar: "الدقهلية",
    cities: [
      city("mansoura", "Mansoura", "المنصورة"),
      city("talkha", "Talkha", "طلخا"),
      city("mit-ghamr", "Mit Ghamr", "ميت غمر"),
      city("bilqas", "Bilqas", "بلقاس"),
      city("sherbin", "Sherbin", "شربين"),
      city("aga", "Aga", "أجا"),
      city("el-senbellawein", "El Senbellawein", "السنبلاوين"),
      city("el-manzala", "El Manzala", "المنزلة"),
      city("dekernes", "Dekernes", "دكرنس"),
      city("gamasa", "Gamasa", "جمصة"),
      city("new-mansoura", "New Mansoura", "المنصورة الجديدة"),
      city("menia-el-nasr", "Menia El Nasr", "منية النصر"),
      city("el-kurdi", "El Kurdi", "الكردي"),
      city("bani-ubaid", "Bani Ubaid", "بني عبيد"),
      city("tami-al-amdid", "Tami Al Amdid", "تمي الأمديد"),
      city("mataria", "Mataria", "المطرية"),
      city("meet-salsil", "Meet Salsil", "ميت سلسيل"),
      city("mahalat-damana", "Mahalat Damana", "محلة دمنة"),
      city("nabroh", "Nabroh", "نبروه"),
    ],
  },
  {
    code: "GH",
    en: "Gharbia",
    ar: "الغربية",
    cities: [
      city("tanta", "Tanta", "طنطا"),
      city("el-mahalla-el-kubra", "El Mahalla El Kubra", "المحلة الكبرى"),
      city("kafr-el-zayat", "Kafr El Zayat", "كفر الزيات"),
      city("zefta", "Zefta", "زفتى"),
      city("samannoud", "Samannoud", "سمنود"),
      city("basyoun", "Basyoun", "بسيون"),
      city("qutour", "Qutour", "قطور"),
      city("el-santa", "El Santa", "السنطة"),
    ],
  },
  {
    code: "MNF",
    en: "Monufia",
    ar: "المنوفية",
    cities: [
      city("shibin-el-kom", "Shibin El Kom", "شبين الكوم"),
      city("sadat-city", "Sadat City", "مدينة السادات"),
      city("menouf", "Menouf", "منوف"),
      city("ashmoun", "Ashmoun", "أشمون"),
      city("quweisna", "Quweisna", "قويسنا"),
      city("berket-el-sabee", "Berket El Sabe", "بركة السبع"),
      city("tala", "Tala", "تلا"),
      city("el-bagour", "El Bagour", "الباجور"),
      city("sars-el-layan", "Sars El-Layan", "سرس الليان"),
      city("al-shohada", "Al Shohada", "الشهداء"),
    ],
  },
  {
    code: "BH",
    en: "Beheira",
    ar: "البحيرة",
    cities: [
      city("damanhur", "Damanhur", "دمنهور"),
      city("kafr-el-dawwar", "Kafr El Dawwar", "كفر الدوار"),
      city("rashid", "Rashid", "رشيد"),
      city("edku", "Edku", "إدكو"),
      city("abu-el-matamir", "Abu El Matamir", "أبو المطامير"),
      city("hosh-eissa", "Hosh Eissa", "حوش عيسى"),
      city("kom-hamada", "Kom Hamada", "كوم حمادة"),
      city("el-delengat", "El Delengat", "الدلنجات"),
      city("wadi-el-natrun", "Wadi El Natrun", "وادي النطرون"),
      city("abu-homs", "Abu Homs", "أبو حمص"),
      city("mahmoudiyah", "Mahmoudiyah", "المحمودية"),
      city("rahmaniyah", "Rahmaniyah", "الرحمانية"),
      city("itai-baroud", "Itai Baroud", "إيتاي البارود"),
      city("shubrakhit", "Shubrakhit", "شبراخيت"),
      city("new-nubaria", "New Nubaria", "النوبارية الجديدة"),
      city("alnoubareya", "Alnoubareya", "النوبارية"),
    ],
  },
  {
    code: "KFS",
    en: "Kafr El Sheikh",
    ar: "كفر الشيخ",
    cities: [
      city("kafr-el-sheikh", "Kafr El Sheikh", "كفر الشيخ"),
      city("desouk", "Desouk", "دسوق"),
      city("baltim", "Baltim", "بلطيم"),
      city("fuwwah", "Fuwwah", "فوه"),
      city("sidi-salem", "Sidi Salem", "سيدي سالم"),
      city("el-hamool", "El Hamool", "الحامول"),
      city("metoubes", "Metoubes", "مطوبس"),
      city("bella", "Bella", "بيلا"),
      city("kafr-el-sheikh-downtown", "Kafr El Sheikh Downtown", "وسط البلد كفر الشيخ"),
      city("burg-al-burullus", "Burg Al Burullus", "برج البرلس"),
      city("masief-baltim", "Masief Baltim", "مصيف بلطيم"),
      city("riyadh", "Riyadh", "الرياض"),
      city("qellen", "Qellen", "قلين"),
      city("sidi-ghazi", "Sidi Ghazi", "سيدي غازي"),
    ],
  },
  {
    code: "DT",
    en: "Damietta",
    ar: "دمياط",
    cities: [
      city("damietta", "Damietta", "دمياط"),
      city("new-damietta", "New Damietta", "دمياط الجديدة"),
      city("ras-el-bar", "Ras El Bar", "رأس البر"),
      city("faraskur", "Faraskur", "فارسكور"),
      city("kafr-saad", "Kafr Saad", "كفر سعد"),
      city("ezbet-el-borg", "Ezbet El Borg", "عزبة البرج"),
      city("zarqa", "Zarqa", "الزرقا"),
      city("alsaru", "Alsaru", "السرو"),
      city("alruwda", "Alruwda", "الروضة"),
      city("kafr-el-batikh", "Kafr El-Batikh", "كفر البطيخ"),
      city("meet-abou-ghalib", "Meet Abou Ghalib", "ميت أبو غالب"),
    ],
  },
  {
    code: "PTS",
    en: "Port Said",
    ar: "بورسعيد",
    cities: [
      city("port-said", "Port Said", "بورسعيد"),
      city("port-fouad", "Port Fouad", "بورفؤاد"),
      city("east-district", "East District", "حي الشرق"),
      city("arab-district", "Arab District", "حي العرب"),
      city("suburbs-district", "Suburbs District", "حي الضواحي"),
      city("zohour", "Zohour", "حي الزهور"),
      city("almanakh", "Almanakh", "حي المناخ"),
    ],
  },
  {
    code: "IS",
    en: "Ismailia",
    ar: "الإسماعيلية",
    cities: [
      city("ismailia", "Ismailia", "الإسماعيلية"),
      city("fayed", "Fayed", "فايد"),
      city("el-qantara", "El Qantara", "القنطرة"),
      city("abu-suwir", "Abu Suwir", "أبو صوير"),
      city("el-tal-el-kebir", "El Tal El Kebir", "التل الكبير"),
      city("qantara-east", "Qantara East", "القنطرة شرق"),
      city("qantara-gharb", "Qantara Gharb", "القنطرة غرب"),
      city("kasasien-el-gedida", "Kasasien El Gedida", "القصاصين الجديدة"),
      city("nefesha", "Nefesha", "نفيشة"),
    ],
  },
  {
    code: "SUZ",
    en: "Suez",
    ar: "السويس",
    cities: [
      city("suez", "Suez", "السويس"),
      city("ain-sokhna", "Ain Sokhna", "العين السخنة"),
      city("ataqa", "Ataqa", "عتاقة"),
      city("suez-district", "Suez District", "حي السويس"),
      city("arbaeen-district", "Arbaeen District", "حي الأربعين"),
      city("faisal-district", "Faisal District", "حي فيصل"),
      city("galala-city", "Galala City", "مدينة الجلالة"),
      city("alganayen", "Alganayen", "الجناين"),
    ],
  },
  {
    code: "SIN",
    en: "North Sinai",
    ar: "شمال سيناء",
    cities: [
      city("arish", "Arish", "العريش"),
      city("bir-el-abd", "Bir El Abd", "بئر العبد"),
      city("sheikh-zuweid", "Sheikh Zuweid", "الشيخ زويد"),
      city("rafah", "Rafah", "رفح"),
      city("nakhl", "Nakhl", "نخل"),
      city("al-hasana", "Al Hasana", "الحسنة"),
    ],
  },
  {
    code: "JS",
    en: "South Sinai",
    ar: "جنوب سيناء",
    cities: [
      city("sharm-el-sheikh", "Sharm El Sheikh", "شرم الشيخ"),
      city("dahab", "Dahab", "دهب"),
      city("nuweiba", "Nuweiba", "نويبع"),
      city("el-tor", "El Tor", "الطور"),
      city("saint-catherine", "Saint Catherine", "سانت كاترين"),
      city("taba", "Taba", "طابا"),
      city("ras-sedr", "Ras Sedr", "رأس سدر"),
      city("abu-redis", "Abu Redis", "أبو رديس"),
      city("abu-zenaima", "Abu Zenaima", "أبو زنيمة"),
    ],
  },
  {
    code: "BA",
    en: "Red Sea",
    ar: "البحر الأحمر",
    cities: [
      city("hurghada", "Hurghada", "الغردقة"),
      city("el-gouna", "El Gouna", "الجونة"),
      city("safaga", "Safaga", "سفاجا"),
      city("marsa-alam", "Marsa Alam", "مرسى علم"),
      city("el-quseir", "El Quseir", "القصير"),
      city("ras-ghareb", "Ras Ghareb", "رأس غارب"),
      city("shalatin", "Shalatin", "الشلاتين"),
      city("halaib", "Halaib", "حلايب"),
      city("aldahar", "Aldahar", "الدهار"),
    ],
  },
  {
    code: "MT",
    en: "Matrouh",
    ar: "مطروح",
    cities: [
      city("marsa-matrouh", "Marsa Matrouh", "مرسى مطروح"),
      city("el-alamein", "El Alamein", "العلمين"),
      city("new-alamein", "New Alamein", "العلمين الجديدة"),
      city("siwa", "Siwa", "سيوة"),
      city("el-dabaa", "El Dabaa", "الضبعة"),
      city("sidi-abdel-rahman", "Sidi Abdel Rahman", "سيدي عبد الرحمن"),
      city("el-hamam", "El Hamam", "الحمام"),
      city("al-nagila", "Al-Nagila", "النجيلة"),
      city("sidi-brani", "Sidi Brani", "سيدي براني"),
      city("salloum", "Salloum", "السلوم"),
    ],
  },
  {
    code: "FYM",
    en: "Faiyum",
    ar: "الفيوم",
    cities: [
      city("faiyum", "Faiyum", "الفيوم"),
      city("sinnuris", "Sinnuris", "سنورس"),
      city("ibsheway", "Ibsheway", "إبشواي"),
      city("tamiya", "Tamiya", "طامية"),
      city("el-wasta", "El Wasta", "الواسطى"),
      city("etsa", "Etsa", "إطسا"),
      city("fayoum-el-gedida", "Fayoum El Gedida", "الفيوم الجديدة"),
      city("yusuf-el-sediaq", "Yusuf El Sediaq", "يوسف الصديق"),
      city("hadqa", "Hadqa", "الحادقة"),
    ],
  },
  {
    code: "BNS",
    en: "Beni Suef",
    ar: "بني سويف",
    cities: [
      city("beni-suef", "Beni Suef", "بني سويف"),
      city("new-beni-suef", "New Beni Suef", "بني سويف الجديدة"),
      city("el-wasta-bns", "El Wasta", "الواسطى"),
      city("nasser", "Nasser", "ناصر"),
      city("biba", "Biba", "ببا"),
      city("el-fashn", "El Fashn", "الفشن"),
      city("ehnasia", "Ehnasia", "إهناسيا"),
      city("somasta", "Somasta", "سمسطا"),
    ],
  },
  {
    code: "MN",
    en: "Minya",
    ar: "المنيا",
    cities: [
      city("minya", "Minya", "المنيا"),
      city("new-minya", "New Minya", "المنيا الجديدة"),
      city("mallawi", "Mallawi", "ملوي"),
      city("beni-mazar", "Beni Mazar", "بني مزار"),
      city("samalut", "Samalut", "سمالوط"),
      city("maghagha", "Maghagha", "مغاغة"),
      city("matay", "Matay", "مطاي"),
      city("abu-qurqas", "Abu Qurqas", "أبو قرقاص"),
      city("deir-mawas", "Deir Mawas", "دير مواس"),
      city("el-adwa", "El Adwa", "العدوة"),
    ],
  },
  {
    code: "AST",
    en: "Asyut",
    ar: "أسيوط",
    cities: [
      city("asyut", "Asyut", "أسيوط"),
      city("new-asyut", "New Asyut", "أسيوط الجديدة"),
      city("abnub", "Abnub", "أبنوب"),
      city("abu-tig", "Abu Tig", "أبو تيج"),
      city("dayrut", "Dayrut", "ديروط"),
      city("manfalut", "Manfalut", "منفلوط"),
      city("el-qusiya", "El Qusiya", "القوصية"),
      city("el-badari", "El Badari", "البداري"),
      city("nasser-city-west-asyut", "Nasser City (West Asyut)", "مدينة ناصر (غرب أسيوط)"),
      city("el-ghanaim", "El Ghanaim", "الغنايم"),
      city("sahel-selim", "Sahel Selim", "ساحل سليم"),
      city("sidfa", "Sidfa", "صدفا"),
    ],
  },
  {
    code: "SHG",
    en: "Sohag",
    ar: "سوهاج",
    cities: [
      city("sohag", "Sohag", "سوهاج"),
      city("new-sohag", "New Sohag", "سوهاج الجديدة"),
      city("akhmim", "Akhmim", "أخميم"),
      city("girga", "Girga", "جرجا"),
      city("tahta", "Tahta", "طهطا"),
      city("el-balyana", "El Balyana", "البلينا"),
      city("tima", "Tima", "طما"),
      city("el-maragha", "El Maragha", "المراغة"),
      city("akhmim-el-gedida", "Akhmim El Gedida", "أخميم الجديدة"),
      city("almunshaa", "Almunshaa", "المنشأة"),
      city("dar-aisalaam", "Dar AISalaam", "دار السلام"),
      city("jahina-al-gharbia", "Jahina Al Gharbia", "جهينة الغربية"),
      city("saqilatuh", "Saqilatuh", "ساقلته"),
      city("alkawthar", "Alkawthar", "الكوثر"),
    ],
  },
  {
    code: "KN",
    en: "Qena",
    ar: "قنا",
    cities: [
      city("qena", "Qena", "قنا"),
      city("nag-hammadi", "Nag Hammadi", "نجع حمادي"),
      city("qus", "Qus", "قوص"),
      city("dishna", "Dishna", "دشنا"),
      city("farshut", "Farshut", "فرشوط"),
      city("qift", "Qift", "قفط"),
      city("new-qena", "New Qena", "قنا الجديدة"),
      city("abu-tesht", "Abu Tesht", "أبو تشت"),
      city("alwaqf", "Alwaqf", "الوقف"),
      city("naqada", "Naqada", "نقادة"),
    ],
  },
  {
    code: "LX",
    en: "Luxor",
    ar: "الأقصر",
    cities: [
      city("luxor", "Luxor", "الأقصر"),
      city("esna", "Esna", "إسنا"),
      city("armant", "Armant", "أرمنت"),
      city("el-tod", "El Tod", "الطود"),
      city("new-luxor", "New Luxor", "الأقصر الجديدة"),
      city("new-tiba", "New Tiba", "طيبة الجديدة"),
      city("al-ziynia", "Al Ziynia", "الزينية"),
      city("al-bayadieh", "Al Bayadieh", "البياضية"),
      city("al-qarna", "Al Qarna", "القرنة"),
    ],
  },
  {
    code: "ASN",
    en: "Aswan",
    ar: "أسوان",
    cities: [
      city("aswan", "Aswan", "أسوان"),
      city("kom-ombo", "Kom Ombo", "كوم أمبو"),
      city("edfu", "Edfu", "إدفو"),
      city("abu-simbel", "Abu Simbel", "أبو سمبل"),
      city("daraw", "Daraw", "دراو"),
      city("aswan-el-gedida", "Aswan El Gedida", "أسوان الجديدة"),
      city("nasr-al-nuba", "Nasr Al Nuba", "نصر النوبة"),
      city("kalabsha", "Kalabsha", "كلابشة"),
      city("al-radisiyah", "Al-Radisiyah", "الرديسية"),
      city("al-basilia", "Al Basilia", "البصيلية"),
      city("al-sibaeia", "Al Sibaeia", "السباعية"),
    ],
  },
  {
    code: "WAD",
    en: "New Valley",
    ar: "الوادي الجديد",
    cities: [
      city("kharga", "Kharga", "الخارجة"),
      city("dakhla", "Dakhla", "الداخلة"),
      city("farafra", "Farafra", "الفرافرة"),
      city("balat", "Balat", "بلاط"),
      city("paris", "Paris", "باريس"),
      city("mout", "Mout", "موط"),
    ],
  },
] as const;

/** Every city, flattened, with the governorate it belongs to. */
export const EGYPT_CITIES: readonly (EgyptCity & { governorate: string })[] =
  EGYPT_GOVERNORATES.flatMap((governorate) =>
    governorate.cities.map((entry) => ({
      ...entry,
      governorate: governorate.code,
    }))
  );

const GOVERNORATES_BY_CODE = new Map(
  EGYPT_GOVERNORATES.map((governorate) => [governorate.code, governorate])
);

const CITIES_BY_SLUG = new Map(EGYPT_CITIES.map((entry) => [entry.slug, entry]));

export function findGovernorate(code?: string | null) {
  return code ? GOVERNORATES_BY_CODE.get(code) : undefined;
}

export function findCity(slug?: string | null) {
  return slug ? CITIES_BY_SLUG.get(slug) : undefined;
}
