-- Disclosures a buyer asks about (per car) and dealership terms (per
-- organization). Additive and nullable: null means "not stated".
-- Generated by `prisma migrate diff`, minus the drift that diff always reports
-- for the hand-written search migrations (searchVector default, trigram names).

-- CreateEnum
CREATE TYPE "ServiceHistory" AS ENUM ('FULL', 'PARTIAL', 'NONE');

-- AlterTable
ALTER TABLE "Car" ADD COLUMN     "accidentFree" BOOLEAN,
ADD COLUMN     "licenseValidUntil" DATE,
ADD COLUMN     "originalPaint" BOOLEAN,
ADD COLUMN     "ownerCount" INTEGER,
ADD COLUMN     "priceNegotiable" BOOLEAN,
ADD COLUMN     "serviceHistory" "ServiceHistory";

-- AlterTable
ALTER TABLE "Organization" ADD COLUMN     "acceptsTradeIn" BOOLEAN,
ADD COLUMN     "allowsInspection" BOOLEAN,
ADD COLUMN     "financingNote" TEXT,
ADD COLUMN     "offersDelivery" BOOLEAN,
ADD COLUMN     "offersFinancing" BOOLEAN;

